const cities = [
  { name: 'Mumbai', country: 'India', description: 'City of Dreams — financial capital with vibrant street life, Bollywood & beaches.', popularActivities: ['Gateway of India', 'Marine Drive Walk', 'Dharavi Tour', 'Juhu Beach'], avgDailyCost: 2500, tags: ['metro', 'beach', 'culture'] },
  { name: 'Delhi', country: 'India', description: 'India\'s capital — rich Mughal history, street food paradise & iconic monuments.', popularActivities: ['Red Fort', 'Qutub Minar', 'India Gate', 'Chandni Chowk Food Walk'], avgDailyCost: 2000, tags: ['history', 'culture', 'food'] },
  { name: 'Goa', country: 'India', description: 'Beach paradise with Portuguese heritage, water sports & vibrant nightlife.', popularActivities: ['Baga Beach', 'Water Sports', 'Old Goa Churches', 'Night Markets'], avgDailyCost: 3000, tags: ['beach', 'party', 'adventure'] },
  { name: 'Jaipur', country: 'India', description: 'Pink City — royal palaces, camel rides & colorful bazaars of Rajasthan.', popularActivities: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Elephant Ride'], avgDailyCost: 1800, tags: ['history', 'culture', 'royal'] },
  { name: 'Kerala', country: 'India', description: 'God\'s Own Country — backwaters, ayurveda, spice gardens & hill stations.', popularActivities: ['Houseboat Cruise', 'Munnar Tea Gardens', 'Kathakali Show', 'Kovalam Beach'], avgDailyCost: 2200, tags: ['nature', 'relaxation', 'adventure'] },
  { name: 'Agra', country: 'India', description: 'Home of the Taj Mahal — Mughal architecture and romance.', popularActivities: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh Sunset'], avgDailyCost: 1500, tags: ['history', 'romance', 'culture'] },
  { name: 'Manali', country: 'India', description: 'Himalayan adventure hub — snow peaks, skiing & river rafting.', popularActivities: ['Rohtang Pass', 'Solang Valley', 'Beas River Rafting', 'Old Manali Walk'], avgDailyCost: 2800, tags: ['adventure', 'nature', 'snow'] },
  { name: 'Udaipur', country: 'India', description: 'City of Lakes — romantic lake palaces & Rajasthani grandeur.', popularActivities: ['Lake Pichola Boat Ride', 'City Palace', 'Sajjangarh Fort', 'Shilpgram'], avgDailyCost: 2000, tags: ['romance', 'history', 'lakes'] },
  { name: 'Varanasi', country: 'India', description: 'Spiritual capital — Ganga ghats, ancient temples & morning aarti.', popularActivities: ['Ganga Aarti', 'Boat Ride', 'Kashi Vishwanath Temple', 'Sarnath'], avgDailyCost: 1200, tags: ['spiritual', 'culture', 'history'] },
  { name: 'Darjeeling', country: 'India', description: 'Queen of Hills — tea gardens, toy train & Himalayan sunrises.', popularActivities: ['Tiger Hill Sunrise', 'Tea Garden Tour', 'Toy Train Ride', 'Batasia Loop'], avgDailyCost: 1800, tags: ['nature', 'tea', 'hills'] },
  { name: 'Rishikesh', country: 'India', description: 'Yoga capital of the world with thrilling river rafting & treks.', popularActivities: ['River Rafting', 'Bungee Jumping', 'Beatles Ashram', 'Triveni Ghat'], avgDailyCost: 1500, tags: ['adventure', 'spiritual', 'yoga'] },
  { name: 'Amritsar', country: 'India', description: 'Holy city of Sikhs — Golden Temple, Wagah Border & legendary food.', popularActivities: ['Golden Temple', 'Wagah Border Ceremony', 'Jallianwala Bagh', 'Amritsari Kulcha'], avgDailyCost: 1300, tags: ['spiritual', 'food', 'culture'] },
  { name: 'Bangkok', country: 'Thailand', description: 'City of Angels — temples, street food, shopping & nightlife.', popularActivities: ['Grand Palace', 'Wat Arun', 'Chatuchak Market', 'Floating Market'], avgDailyCost: 3500, tags: ['culture', 'food', 'shopping'] },
  { name: 'Bali', country: 'Indonesia', description: 'Island paradise — rice terraces, temples, surf & spiritual retreats.', popularActivities: ['Tanah Lot Temple', 'Ubud Rice Terraces', 'Seminyak Beach', 'Kecak Dance'], avgDailyCost: 3000, tags: ['beach', 'culture', 'relaxation'] },
  { name: 'Singapore', country: 'Singapore', description: 'Garden city — futuristic skyline, multicultural food & world-class attractions.', popularActivities: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Hawker Centers'], avgDailyCost: 8000, tags: ['metro', 'food', 'modern'] },
  { name: 'Dubai', country: 'UAE', description: 'Desert luxury — sky-high skyscrapers, desert safaris & world records.', popularActivities: ['Burj Khalifa', 'Desert Safari', 'Dubai Mall', 'Palm Jumeirah'], avgDailyCost: 10000, tags: ['luxury', 'shopping', 'adventure'] },
  { name: 'Paris', country: 'France', description: 'City of Love — Eiffel Tower, fine dining, art & fashion.', popularActivities: ['Eiffel Tower', 'Louvre Museum', 'Notre Dame', 'Seine River Cruise'], avgDailyCost: 12000, tags: ['romance', 'culture', 'food'] },
  { name: 'New York', country: 'USA', description: 'The Big Apple — Times Square, museums, Broadway & iconic skyline.', popularActivities: ['Times Square', 'Central Park', 'Statue of Liberty', 'Broadway Show'], avgDailyCost: 15000, tags: ['metro', 'culture', 'shopping'] },
  { name: 'Tokyo', country: 'Japan', description: 'Futuristic meets traditional — anime, sushi, shrines & cherry blossoms.', popularActivities: ['Senso-ji Temple', 'Shibuya Crossing', 'Mount Fuji Day Trip', 'Tsukiji Market'], avgDailyCost: 9000, tags: ['culture', 'food', 'modern'] },
  { name: 'Maldives', country: 'Maldives', description: 'Overwater paradise — crystal lagoons, coral reefs & ultimate luxury.', popularActivities: ['Snorkeling', 'Dolphin Watching', 'Overwater Bungalow Stay', 'Sunset Cruise'], avgDailyCost: 20000, tags: ['luxury', 'beach', 'relaxation'] },
];

module.exports = cities;
